#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: meson
# autospec version: v19
# autospec commit: f35655a
#
Name     : sysprof
Version  : 47.0
Release  : 25
URL      : https://download.gnome.org/sources/sysprof/47/sysprof-47.0.tar.xz
Source0  : https://download.gnome.org/sources/sysprof/47/sysprof-47.0.tar.xz
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0 BSD-2-Clause-Patent GPL-2.0 GPL-3.0
Requires: sysprof-bin = %{version}-%{release}
Requires: sysprof-data = %{version}-%{release}
Requires: sysprof-lib = %{version}-%{release}
Requires: sysprof-libexec = %{version}-%{release}
Requires: sysprof-license = %{version}-%{release}
Requires: sysprof-locales = %{version}-%{release}
Requires: sysprof-services = %{version}-%{release}
BuildRequires : buildreq-gnome
BuildRequires : buildreq-meson
BuildRequires : gettext
BuildRequires : gettext-dev
BuildRequires : json-glib-dev
BuildRequires : libdazzle-dev
BuildRequires : pkgconfig(json-glib-1.0)
BuildRequires : pkgconfig(libadwaita-1)
BuildRequires : pkgconfig(libdazzle-1.0)
BuildRequires : pkgconfig(libdex-1)
BuildRequires : pkgconfig(libpanel-1)
BuildRequires : pkgconfig(libunwind-generic)
BuildRequires : pkgconfig(polkit-gobject-1)
BuildRequires : polkit-dev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
Sysprof is a sampling profiler that uses a kernel module to generate
stacktraces which are then interpreted by the userspace program
"sysprof".

%package bin
Summary: bin components for the sysprof package.
Group: Binaries
Requires: sysprof-data = %{version}-%{release}
Requires: sysprof-libexec = %{version}-%{release}
Requires: sysprof-license = %{version}-%{release}
Requires: sysprof-services = %{version}-%{release}

%description bin
bin components for the sysprof package.


%package data
Summary: data components for the sysprof package.
Group: Data

%description data
data components for the sysprof package.


%package dev
Summary: dev components for the sysprof package.
Group: Development
Requires: sysprof-lib = %{version}-%{release}
Requires: sysprof-bin = %{version}-%{release}
Requires: sysprof-data = %{version}-%{release}
Provides: sysprof-devel = %{version}-%{release}
Requires: sysprof = %{version}-%{release}

%description dev
dev components for the sysprof package.


%package doc
Summary: doc components for the sysprof package.
Group: Documentation

%description doc
doc components for the sysprof package.


%package lib
Summary: lib components for the sysprof package.
Group: Libraries
Requires: sysprof-data = %{version}-%{release}
Requires: sysprof-libexec = %{version}-%{release}
Requires: sysprof-license = %{version}-%{release}

%description lib
lib components for the sysprof package.


%package libexec
Summary: libexec components for the sysprof package.
Group: Default
Requires: sysprof-license = %{version}-%{release}

%description libexec
libexec components for the sysprof package.


%package license
Summary: license components for the sysprof package.
Group: Default

%description license
license components for the sysprof package.


%package locales
Summary: locales components for the sysprof package.
Group: Default

%description locales
locales components for the sysprof package.


%package services
Summary: services components for the sysprof package.
Group: Systemd services
Requires: systemd

%description services
services components for the sysprof package.


%package staticdev
Summary: staticdev components for the sysprof package.
Group: Default
Requires: sysprof-dev = %{version}-%{release}

%description staticdev
staticdev components for the sysprof package.


%prep
%setup -q -n sysprof-47.0
cd %{_builddir}/sysprof-47.0
pushd ..
cp -a sysprof-47.0 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1726774558
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
meson --libdir=lib64 --prefix=/usr --buildtype=plain   builddir
ninja -v -C builddir
GOAMD64=v3
CFLAGS="$CFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 " CXXFLAGS="$CXXFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 " LDFLAGS="$LDFLAGS -march=x86-64-v3 " meson --libdir=lib64 --prefix=/usr --buildtype=plain   builddiravx2
ninja -v -C builddiravx2

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
meson test -C builddir --print-errorlogs || :
cd ../buildavx2;
meson test -C builddir --print-errorlogs || : || :

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
mkdir -p %{buildroot}/usr/share/package-licenses/sysprof
cp %{_builddir}/sysprof-%{version}/COPYING %{buildroot}/usr/share/package-licenses/sysprof/8624bcdae55baeef00cd11d5dfcfa60f68710a02 || :
cp %{_builddir}/sysprof-%{version}/COPYING.gpl-2 %{buildroot}/usr/share/package-licenses/sysprof/dfac199a7539a404407098a2541b9482279f690d || :
cp %{_builddir}/sysprof-%{version}/contrib/eggbitset/COPYING %{buildroot}/usr/share/package-licenses/sysprof/2b8b815229aa8a61e483fb4ba0588b8b6c491890 || :
cp %{_builddir}/sysprof-%{version}/src/libsysprof-capture/COPYING %{buildroot}/usr/share/package-licenses/sysprof/f0464855038f72585350235098599184ac3b3810 || :
cp %{_builddir}/sysprof-%{version}/src/libsysprof/timsort/COPYING %{buildroot}/usr/share/package-licenses/sysprof/2b8b815229aa8a61e483fb4ba0588b8b6c491890 || :
GOAMD64=v3
DESTDIR=%{buildroot}-v3 ninja -C builddiravx2 install
GOAMD64=v2
DESTDIR=%{buildroot} ninja -C builddir install
%find_lang sysprof
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/V3/usr/bin/sysprof
/V3/usr/bin/sysprof-agent
/V3/usr/bin/sysprof-cli
/usr/bin/sysprof
/usr/bin/sysprof-agent
/usr/bin/sysprof-cli

%files data
%defattr(-,root,root,-)
/usr/share/applications/org.gnome.Sysprof.desktop
/usr/share/dbus-1/interfaces/org.gnome.Sysprof.Agent.xml
/usr/share/dbus-1/interfaces/org.gnome.Sysprof3.Profiler.xml
/usr/share/dbus-1/interfaces/org.gnome.Sysprof3.Service.xml
/usr/share/dbus-1/system-services/org.gnome.Sysprof3.service
/usr/share/dbus-1/system.d/org.gnome.Sysprof3.conf
/usr/share/icons/hicolor/scalable/actions/sysprof-allocations.svg
/usr/share/icons/hicolor/scalable/actions/sysprof-battery.svg
/usr/share/icons/hicolor/scalable/actions/sysprof-calgraph.svg
/usr/share/icons/hicolor/scalable/actions/sysprof-cli.svg
/usr/share/icons/hicolor/scalable/actions/sysprof-cpu.svg
/usr/share/icons/hicolor/scalable/actions/sysprof-disk.svg
/usr/share/icons/hicolor/scalable/actions/sysprof-gtk.svg
/usr/share/icons/hicolor/scalable/actions/sysprof-library.svg
/usr/share/icons/hicolor/scalable/actions/sysprof-memory.svg
/usr/share/icons/hicolor/scalable/actions/sysprof-networking.svg
/usr/share/icons/hicolor/scalable/actions/sysprof-rapl.svg
/usr/share/icons/hicolor/scalable/actions/sysprof-trace-app.svg
/usr/share/icons/hicolor/scalable/apps/org.gnome.Sysprof.svg
/usr/share/icons/hicolor/symbolic/apps/org.gnome.Sysprof-symbolic.svg
/usr/share/metainfo/org.gnome.Sysprof.appdata.xml
/usr/share/mime-packages/sysprof-mime.xml
/usr/share/polkit-1/actions/org.gnome.sysprof3.policy

%files dev
%defattr(-,root,root,-)
/usr/include/sysprof-6/sysprof-address.h
/usr/include/sysprof-6/sysprof-battery-charge.h
/usr/include/sysprof-6/sysprof-bundled-symbolizer.h
/usr/include/sysprof-6/sysprof-callgraph-frame.h
/usr/include/sysprof-6/sysprof-callgraph-symbol.h
/usr/include/sysprof-6/sysprof-callgraph.h
/usr/include/sysprof-6/sysprof-capture-condition.h
/usr/include/sysprof-6/sysprof-capture-cursor.h
/usr/include/sysprof-6/sysprof-capture-reader.h
/usr/include/sysprof-6/sysprof-capture-types.h
/usr/include/sysprof-6/sysprof-capture-writer.h
/usr/include/sysprof-6/sysprof-capture.h
/usr/include/sysprof-6/sysprof-category-summary.h
/usr/include/sysprof-6/sysprof-clock.h
/usr/include/sysprof-6/sysprof-collector.h
/usr/include/sysprof-6/sysprof-cpu-info.h
/usr/include/sysprof-6/sysprof-cpu-usage.h
/usr/include/sysprof-6/sysprof-dbus-monitor.h
/usr/include/sysprof-6/sysprof-diagnostic.h
/usr/include/sysprof-6/sysprof-disk-usage.h
/usr/include/sysprof-6/sysprof-document-allocation.h
/usr/include/sysprof-6/sysprof-document-counter-value.h
/usr/include/sysprof-6/sysprof-document-counter.h
/usr/include/sysprof-6/sysprof-document-ctrdef.h
/usr/include/sysprof-6/sysprof-document-ctrset.h
/usr/include/sysprof-6/sysprof-document-dbus-message.h
/usr/include/sysprof-6/sysprof-document-exit.h
/usr/include/sysprof-6/sysprof-document-file-chunk.h
/usr/include/sysprof-6/sysprof-document-file.h
/usr/include/sysprof-6/sysprof-document-fork.h
/usr/include/sysprof-6/sysprof-document-frame.h
/usr/include/sysprof-6/sysprof-document-jitmap.h
/usr/include/sysprof-6/sysprof-document-loader.h
/usr/include/sysprof-6/sysprof-document-log.h
/usr/include/sysprof-6/sysprof-document-mark.h
/usr/include/sysprof-6/sysprof-document-metadata.h
/usr/include/sysprof-6/sysprof-document-mmap.h
/usr/include/sysprof-6/sysprof-document-overlay.h
/usr/include/sysprof-6/sysprof-document-process.h
/usr/include/sysprof-6/sysprof-document-sample.h
/usr/include/sysprof-6/sysprof-document-traceable.h
/usr/include/sysprof-6/sysprof-document.h
/usr/include/sysprof-6/sysprof-elf-symbolizer.h
/usr/include/sysprof-6/sysprof-energy-usage.h
/usr/include/sysprof-6/sysprof-enums.h
/usr/include/sysprof-6/sysprof-instrument.h
/usr/include/sysprof-6/sysprof-jitmap-symbolizer.h
/usr/include/sysprof-6/sysprof-kallsyms-symbolizer.h
/usr/include/sysprof-6/sysprof-macros.h
/usr/include/sysprof-6/sysprof-malloc-tracing.h
/usr/include/sysprof-6/sysprof-mark-catalog.h
/usr/include/sysprof-6/sysprof-memory-usage.h
/usr/include/sysprof-6/sysprof-mount.h
/usr/include/sysprof-6/sysprof-multi-symbolizer.h
/usr/include/sysprof-6/sysprof-network-usage.h
/usr/include/sysprof-6/sysprof-no-symbolizer.h
/usr/include/sysprof-6/sysprof-platform.h
/usr/include/sysprof-6/sysprof-power-profile.h
/usr/include/sysprof-6/sysprof-profiler.h
/usr/include/sysprof-6/sysprof-proxied-instrument.h
/usr/include/sysprof-6/sysprof-recording.h
/usr/include/sysprof-6/sysprof-sampler.h
/usr/include/sysprof-6/sysprof-scheduler-details.h
/usr/include/sysprof-6/sysprof-spawnable.h
/usr/include/sysprof-6/sysprof-subprocess-output.h
/usr/include/sysprof-6/sysprof-symbol.h
/usr/include/sysprof-6/sysprof-symbolizer.h
/usr/include/sysprof-6/sysprof-symbols-bundle.h
/usr/include/sysprof-6/sysprof-system-logs.h
/usr/include/sysprof-6/sysprof-thread-info.h
/usr/include/sysprof-6/sysprof-time-span.h
/usr/include/sysprof-6/sysprof-tracefd-consumer.h
/usr/include/sysprof-6/sysprof-tracer.h
/usr/include/sysprof-6/sysprof-version-macros.h
/usr/include/sysprof-6/sysprof-version.h
/usr/include/sysprof-6/sysprof.h
/usr/lib64/pkgconfig/sysprof-6.pc
/usr/lib64/pkgconfig/sysprof-capture-4.pc

%files doc
%defattr(0644,root,root,0755)
/usr/share/help/C/sysprof/faq.page
/usr/share/help/C/sysprof/figures/Sysprof.svg
/usr/share/help/C/sysprof/index.page
/usr/share/help/C/sysprof/introduction.page
/usr/share/help/C/sysprof/legal.xml
/usr/share/help/C/sysprof/profiling.page
/usr/share/help/ca/sysprof/faq.page
/usr/share/help/ca/sysprof/figures/Sysprof.svg
/usr/share/help/ca/sysprof/index.page
/usr/share/help/ca/sysprof/introduction.page
/usr/share/help/ca/sysprof/legal.xml
/usr/share/help/ca/sysprof/profiling.page
/usr/share/help/cs/sysprof/faq.page
/usr/share/help/cs/sysprof/figures/Sysprof.svg
/usr/share/help/cs/sysprof/index.page
/usr/share/help/cs/sysprof/introduction.page
/usr/share/help/cs/sysprof/legal.xml
/usr/share/help/cs/sysprof/profiling.page
/usr/share/help/da/sysprof/faq.page
/usr/share/help/da/sysprof/figures/Sysprof.svg
/usr/share/help/da/sysprof/index.page
/usr/share/help/da/sysprof/introduction.page
/usr/share/help/da/sysprof/legal.xml
/usr/share/help/da/sysprof/profiling.page
/usr/share/help/de/sysprof/faq.page
/usr/share/help/de/sysprof/figures/Sysprof.svg
/usr/share/help/de/sysprof/index.page
/usr/share/help/de/sysprof/introduction.page
/usr/share/help/de/sysprof/legal.xml
/usr/share/help/de/sysprof/profiling.page
/usr/share/help/el/sysprof/faq.page
/usr/share/help/el/sysprof/figures/Sysprof.svg
/usr/share/help/el/sysprof/index.page
/usr/share/help/el/sysprof/introduction.page
/usr/share/help/el/sysprof/legal.xml
/usr/share/help/el/sysprof/profiling.page
/usr/share/help/es/sysprof/faq.page
/usr/share/help/es/sysprof/figures/Sysprof.svg
/usr/share/help/es/sysprof/index.page
/usr/share/help/es/sysprof/introduction.page
/usr/share/help/es/sysprof/legal.xml
/usr/share/help/es/sysprof/profiling.page
/usr/share/help/eu/sysprof/faq.page
/usr/share/help/eu/sysprof/figures/Sysprof.svg
/usr/share/help/eu/sysprof/index.page
/usr/share/help/eu/sysprof/introduction.page
/usr/share/help/eu/sysprof/legal.xml
/usr/share/help/eu/sysprof/profiling.page
/usr/share/help/fr/sysprof/faq.page
/usr/share/help/fr/sysprof/figures/Sysprof.svg
/usr/share/help/fr/sysprof/index.page
/usr/share/help/fr/sysprof/introduction.page
/usr/share/help/fr/sysprof/legal.xml
/usr/share/help/fr/sysprof/profiling.page
/usr/share/help/hu/sysprof/faq.page
/usr/share/help/hu/sysprof/figures/Sysprof.svg
/usr/share/help/hu/sysprof/index.page
/usr/share/help/hu/sysprof/introduction.page
/usr/share/help/hu/sysprof/legal.xml
/usr/share/help/hu/sysprof/profiling.page
/usr/share/help/id/sysprof/faq.page
/usr/share/help/id/sysprof/figures/Sysprof.svg
/usr/share/help/id/sysprof/index.page
/usr/share/help/id/sysprof/introduction.page
/usr/share/help/id/sysprof/legal.xml
/usr/share/help/id/sysprof/profiling.page
/usr/share/help/ko/sysprof/faq.page
/usr/share/help/ko/sysprof/figures/Sysprof.svg
/usr/share/help/ko/sysprof/index.page
/usr/share/help/ko/sysprof/introduction.page
/usr/share/help/ko/sysprof/legal.xml
/usr/share/help/ko/sysprof/profiling.page
/usr/share/help/pl/sysprof/faq.page
/usr/share/help/pl/sysprof/figures/Sysprof.svg
/usr/share/help/pl/sysprof/index.page
/usr/share/help/pl/sysprof/introduction.page
/usr/share/help/pl/sysprof/legal.xml
/usr/share/help/pl/sysprof/profiling.page
/usr/share/help/pt_BR/sysprof/faq.page
/usr/share/help/pt_BR/sysprof/figures/Sysprof.svg
/usr/share/help/pt_BR/sysprof/index.page
/usr/share/help/pt_BR/sysprof/introduction.page
/usr/share/help/pt_BR/sysprof/legal.xml
/usr/share/help/pt_BR/sysprof/profiling.page
/usr/share/help/ru/sysprof/faq.page
/usr/share/help/ru/sysprof/figures/Sysprof.svg
/usr/share/help/ru/sysprof/index.page
/usr/share/help/ru/sysprof/introduction.page
/usr/share/help/ru/sysprof/legal.xml
/usr/share/help/ru/sysprof/profiling.page
/usr/share/help/sv/sysprof/faq.page
/usr/share/help/sv/sysprof/figures/Sysprof.svg
/usr/share/help/sv/sysprof/index.page
/usr/share/help/sv/sysprof/introduction.page
/usr/share/help/sv/sysprof/legal.xml
/usr/share/help/sv/sysprof/profiling.page
/usr/share/help/uk/sysprof/faq.page
/usr/share/help/uk/sysprof/figures/Sysprof.svg
/usr/share/help/uk/sysprof/index.page
/usr/share/help/uk/sysprof/introduction.page
/usr/share/help/uk/sysprof/legal.xml
/usr/share/help/uk/sysprof/profiling.page

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/libsysprof-6.so.6.0.0
/V3/usr/lib64/libsysprof-memory-6.so
/V3/usr/lib64/libsysprof-speedtrack-6.so
/V3/usr/lib64/libsysprof-tracer-6.so
/usr/lib64/libsysprof-6.so
/usr/lib64/libsysprof-6.so.6
/usr/lib64/libsysprof-6.so.6.0.0
/usr/lib64/libsysprof-memory-6.so
/usr/lib64/libsysprof-speedtrack-6.so
/usr/lib64/libsysprof-tracer-6.so

%files libexec
%defattr(-,root,root,-)
/V3/usr/libexec/sysprofd
/usr/libexec/sysprofd

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/sysprof/2b8b815229aa8a61e483fb4ba0588b8b6c491890
/usr/share/package-licenses/sysprof/8624bcdae55baeef00cd11d5dfcfa60f68710a02
/usr/share/package-licenses/sysprof/dfac199a7539a404407098a2541b9482279f690d
/usr/share/package-licenses/sysprof/f0464855038f72585350235098599184ac3b3810

%files services
%defattr(-,root,root,-)
/usr/lib/systemd/system/sysprof3.service

%files staticdev
%defattr(-,root,root,-)
/usr/lib64/libsysprof-capture-4.a

%files locales -f sysprof.lang
%defattr(-,root,root,-)

