#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : sysprof
Version  : 3.46.0
Release  : 20
URL      : https://download.gnome.org/sources/sysprof/3.46/sysprof-3.46.0.tar.xz
Source0  : https://download.gnome.org/sources/sysprof/3.46/sysprof-3.46.0.tar.xz
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-2-Clause-Patent GPL-2.0 GPL-3.0
BuildRequires : buildreq-gnome
BuildRequires : buildreq-meson
BuildRequires : gettext
BuildRequires : gettext-dev
BuildRequires : libdazzle-dev
BuildRequires : pkgconfig(libdazzle-1.0)
BuildRequires : pkgconfig(libunwind-generic)
BuildRequires : pkgconfig(polkit-gobject-1)
BuildRequires : polkit-dev

%description
Sysprof is a sampling profiler that uses a kernel module to generate
stacktraces which are then interpreted by the userspace program
"sysprof".

%prep
%setup -q -n sysprof-3.46.0
cd %{_builddir}/sysprof-3.46.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1663965931
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
CFLAGS="$CFLAGS" CXXFLAGS="$CXXFLAGS" LDFLAGS="$LDFLAGS" meson --libdir=lib64 --prefix=/usr --buildtype=plain -Denable_gtk=true \
-Ddebugdir=/usr/lib/debug \
-Dhelp=true \
-Denable_tests=false  builddir
ninja -v -C builddir

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
meson test -C builddir --print-errorlogs || :

%install
mkdir -p %{buildroot}/usr/share/package-licenses/sysprof
cp %{_builddir}/sysprof-%{version}/COPYING %{buildroot}/usr/share/package-licenses/sysprof/8624bcdae55baeef00cd11d5dfcfa60f68710a02 || :
cp %{_builddir}/sysprof-%{version}/COPYING.gpl-2 %{buildroot}/usr/share/package-licenses/sysprof/dfac199a7539a404407098a2541b9482279f690d || :
cp %{_builddir}/sysprof-%{version}/src/libsysprof-capture/COPYING %{buildroot}/usr/share/package-licenses/sysprof/f0464855038f72585350235098599184ac3b3810 || :
DESTDIR=%{buildroot} ninja -C builddir install

%files
%defattr(-,root,root,-)
